[platformio]
default_envs = xiao_esp32s3, xiao_esp32c3, xiao_esp32c6, xiao_esp32c5

[env]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.311/platform-espressif32.zip
framework = arduino
monitor_speed = 115200
board_build.partitions = partitions.csv
board_upload.maximum_size = 6291456
extra_scripts = pre:scripts/build.py
build_flags =
  -DCORE_DEBUG_LEVEL=0
lib_deps =
  h2zero/NimBLE-Arduino@2.5.1
  bblanchon/ArduinoJson@7.4.2

[env:xiao_esp32s3]
board = seeed_xiao_esp32s3
build_unflags = -DARDUINO_USB_MODE=1 -DARDUINO_USB_CDC_ON_BOOT=1
build_flags =
  ${env.build_flags}
  -DARDUINO_USB_MODE=0
  -DARDUINO_USB_CDC_ON_BOOT=0

[env:xiao_esp32c3]
board = seeed_xiao_esp32c3
board_build.partitions = partitions_4mb.csv
board_upload.maximum_size = 3145728

[env:xiao_esp32c6]
board = seeed_xiao_esp32c6
board_build.partitions = partitions_4mb.csv
board_upload.maximum_size = 3145728

[env:xiao_esp32c5]
board = seeed_xiao_esp32c5
