const fs = require('node:fs');
const vm = require('node:vm');
const assert = require('node:assert/strict');
const path = require('node:path');
const context = vm.createContext({TextEncoder});
vm.runInContext(fs.readFileSync(path.join(__dirname,'../web/presets.js'),'utf8')+'\nglobalThis.presets = Presets;',context);
const P=context.presets, usb={usbMidi:true,usbKeyboard:true}, ble={usbMidi:false,usbKeyboard:false};
const config={schemaVersion:1,network:{ssid:'test',password:'secret',oscHost:'192.168.1.2',oscPort:9000},chains:Array.from({length:28},(_,input)=>({input,actions:[]}))};
config.chains[0].actions=[{protocol:'wait',delayMs:123},{protocol:'midi',transport:'both',delayMs:0,message:'noteOn',channel:1,number:48,value:127}];
config.chains[1].actions=[{protocol:'keyboard',transport:'usb',delayMs:0,message:'keyUp',usage:104,modifiers:0}];
config.chains[27].actions=[{protocol:'osc',transport:'wifi',delayMs:0,address:'/test',type:'string',value:'hello'}];
const normalized=v=>JSON.parse(JSON.stringify(v));
const full=P.full(config);
const bulkFull=P.full(config);
bulkFull.chains[2].actions=[{protocol:'midi',message:'allNotesOn',delayMs:0,value:88},{protocol:'midi',message:'allNotesOff',delayMs:0}];
assert.deepEqual(normalized(P.read(bulkFull,'full',ble).config.chains[2]),normalized(bulkFull.chains[2]));
bulkFull.chains[2].actions[0].value=0;assert.throws(()=>P.read(bulkFull,'full',ble));
assert.deepEqual(normalized(P.read(full,'full',usb).config),config);
const converted=P.read(full,'full',ble);
assert.equal(converted.converted,2);
assert.equal(converted.config.chains[0].actions[1].transport,'ble');
assert.equal(full.chains[0].actions[1].transport,'both');
const key=P.key(config,0);
assert.equal(key.chains.length,2);
assert.deepEqual(normalized(P.read(key,'key',usb).chains),config.chains.slice(0,2));
assert.equal(P.read(key,'key',ble).converted,2);
assert.throws(()=>P.read(key,'full',usb));
assert.throws(()=>P.read(full,'key',usb));
assert.throws(()=>P.key(config,13));
assert.throws(()=>P.read({...full,version:99},'full',usb));
function invalid(change){const copy=normalized(full);change(copy);assert.throws(()=>P.read(copy,'full',usb));}
invalid(v=>v.chains[1].input=0);
invalid(v=>v.chains.pop());
invalid(v=>v.chains[0].actions[0].delayMs=-1);
invalid(v=>v.chains[0].actions[0].delayMs=86400001);
invalid(v=>v.chains[0].actions[0].delayMs=1.5);
invalid(v=>v.chains[0].actions[1].value=0);
invalid(v=>v.chains[0].actions[1].delayMs=10);
invalid(v=>v.chains[0].actions=Array(9).fill({protocol:'wait',delayMs:1}));
invalid(v=>v.chains[1].actions[0].transport='both');
invalid(v=>v.network.ssid='あ'.repeat(11));
invalid(v=>v.network.password='a\0b');
invalid(v=>v.network.oscHost='256.1.2.3');
invalid(v=>v.network.oscPort=0);
// Action order and file source are not mutated; full export owns an independent copy.
assert.deepEqual(normalized(full.chains[0].actions.map(a=>a.protocol)),['wait','midi']);
full.network.ssid='changed';assert.equal(config.network.ssid,'test');
console.log('PASS Key/Full round-trip, Wait order, encoder/network preservation, BLE adaptation, invalid imports, no source mutation');
